set +u
cd ${TMPDIR:=/tmp}

touch 1=bar
foo=([10]="bar")
echo ${foo[0]}
rm 1=bar

cd $OLDPWD

foo=(a b c d e f g)
echo ${foo[@]}

# quoted reserved words are ok
foo=(\for \case \if \then \else)
echo ${foo[@]}

# quoted metacharacters are ok
foo=( [1]='<>' [2]='<' [3]='>' [4]='!' )
echo ${foo[@]}

# numbers are just words when not in a redirection context
foo=( 12 14 16 18 20 )
echo ${foo[@]}

foo=( 4414758999202 )
echo ${foo[@]}

# this was a bug in all versions of bash 2.x up to and including bash-2.04
declare -a ddd=(aaa
bbb)
echo ${ddd[@]}

# errors until post-bash-2.05a; now reserved words are OK
foo=(a b c for case if then else)

foo=(for case if then else)

# errors
metas=( <> < > ! )
metas=( [1]=<> [2]=< [3]=> [4]=! )

# various expansions that didn't really work right until post-bash-2.04
foo='abc'
echo ${foo[0]} ${#foo[0]}
echo ${foo[1]} ${#foo[1]}
echo ${foo[@]} ${#foo[@]}
echo ${foo[*]} ${#foo[*]}

foo=''
echo ${foo[0]} ${#foo[0]}
echo ${foo[1]} ${#foo[1]}
echo ${foo[@]} ${#foo[@]}
echo ${foo[*]} ${#foo[*]}

# new expansions added after bash-2.05b
x[0]=zero
x[1]=one
x[4]=four
x[10]=ten

recho ${!x[@]}
recho "${!x[@]}"
recho ${!x[*]}
recho "${!x[*]}"

# sparse array tests for code fixed in bash-3.0
unset av
av[1]='one'
av[2]=''

av[3]=three
av[5]=five
av[7]=seven

echo include null element -- expect one
echo ${av[@]:1:2}	# what happens when we include a null element?
echo include unset element -- expect three five
echo ${av[@]:3:2}	# what happens when we include an unset element?
echo start at unset element -- expect five seven
echo ${av[@]:4:2}	# what happens when we start at an unset element?

echo too many elements -- expect three five seven
echo ${av[@]:3:5}	# how about too many elements?

echo positive offset - expect five seven
echo ${av[@]:5:2}
echo negative offset to unset element - expect seven
echo ${av[@]: -2:2}

echo positive offset 2 - expect seven
echo ${av[@]: 6:2}
echo negative offset 2 - expect seven
echo ${av[@]: -1:2}

echo out-of-range offset
echo ${av[@]:12}

# parsing problems and other inconsistencies not fixed until post bash-3.0
unset x
declare -a x=(')' $$)
[ ${x[1]} -eq $$ ] || echo bad

unset x
declare -a x=(a b c d e)
echo ${x[4]}

z=([1]=one [4]=four [7]=seven [10]=ten)

echo ${#z[@]}

echo ${!z[@]}

unset x
declare -a x=(a \'b  c\')

echo "${x[1]}"

unset x
declare -a x=(a 'b  c')

echo "${x[1]}"

unset x
declare -a x=($0)
[ "${x[@]}" = $0 ] || echo double expansion of \$0
declare -a x=(\$0)
echo "${x[@]}"

unset A Z
Z='a b'
A=( X=$Z )
declare -p A

# combine with brace expansion
letters=( {0..9} )
echo "${letters["{2..6}"]}"

# tests for assigning to noassign array variables
BASH_ARGC=(xxx) ; echo FIN1:$?
BASH_ARGC=foio ; echo FIN2:$?
declare BASH_ARGC=(xxx) ; echo FIN3:$?
declare BASH_ARGC=foio ; echo FIN4:$?
BASH_ARGV[1]=foo ; echo FIN5:$?
declare BASH_ARGV[1]=foo ; echo FIN6:$?
