#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# in posix mode, assignment statements preceding special builtins are
# reflected in the shell environment.  `.' and `eval' need special-case
# code.

# test behavior of command builtin after changing it to a pseudo-keyword (was builtins7.sub)

: ${THIS_SH:=./bash}

${THIS_SH} -c 'command . notthere ; echo one' bash
${THIS_SH} -c '. notthere ; echo two' bash

${THIS_SH} -o posix -c 'command . notthere ; echo one' bash
${THIS_SH} -o posix -c '. notthere ; echo two' bash

command ; echo $?
command -- ; echo $?
command -p ; echo $?
command -p -- ; echo $?

command recho one; echo $?
command -- recho two; echo $?
command -p echo three; echo $?
command -p -- echo four ; echo $?

command ''
echo $?

command -p
echo $?

${THIS_SH} -c 'set -e ; command false ; echo after' bash

command command command -p . notthere ; echo after 1
command -p command command . notthere ; echo after 2

command -p command -V type

set -x
command -v type
command command -v type
command -p command -v type
command -p -- command -v type
set +x

