#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# test behavior of shopt xpg_echo (was builtins2.sub)

# in posix mode, assignment statements preceding special builtins are
# reflected in the shell environment.  `.' and `eval' need special-case
# code.

USG_ECHO=off
shopt -q xpg_echo && USG_ECHO=on

shopt -u xpg_echo
echo 'a\n\n\nb'

shopt -s xpg_echo
echo 'a\n\n\nb'

echo -p
set -o posix
echo 'a\tb\tc'
