#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# error messages on history file read and write errors

: ${TMPDIR:=/tmp}

cd $TMPDIR || exit 1

FILENAME=notthere
DIRNAME=histdir

unset HISTTIMEFORMAT
rm -f $FILENAME

trap 'rm -f $FILENAME ; rm -rf $DIRNAME' 0 1 2 3 6 15

HISTFILE=/dev/null
set -o history

history -r /dev/null	# should succeed
history -r notthere	# failure

history -w		# should succeed
history -w $FILENAME	# should succeed

chmod 200 $FILENAME
history -r $FILENAME

history -r .

mkdir $DIRNAME
touch $DIRNAME/$FILENAME
chmod 555 $DIRNAME

history -w $DIRNAME
history -w $DIRNAME/$FILENAME

chmod u+w $DIRNAME

history -w nodir/$FILENAME
