# test out wait -n framework

set -m

sleep 20 &
{ sleep 2; exit 12; } &
sleep 20 &

wait -n
echo $?

jobs
disown -a

{ sleep 1 ; exit 4; } &
{ sleep 2 ; exit 5; } & bgpid1=$!
{ sleep 4 ; exit 6; } &

wait -p wvar -n %2 %3
case "$wvar" in
$bgpid1)	echo $?: ok 1;;
*)		echo bad 1;;
esac

{ sleep 1 ; exit 2; } & bgpid2=$!
wait -p wvar -n %8 $!
case $wvar in
$bgpid2)	echo $?: ok 2;;
*)		echo bad 2;;
esac

disown -a

{ sleep 3; exit 1; } & { sleep 1; exit 2; } & bgpid3=$!
{ sleep 3; exit 3; } & { sleep 3; exit 4; } &

wait -n -p wpid %1 %2 %3 %4

case $wpid in
$bgpid3)	echo $?: ok 3;;
*)		echo bad 3 ;;
esac

disown -a

unset bgpid1 bgpid2 bgpid3
unset wpid

# now that we have no jobs, make sure that wait -n -p var leaves var unset
jobs
wait -n -p wpid
echo $wpid $?

# make sure wait -p var does something useful without the -n option
jobs
wait -p wpid
declare -p wpid

# let's check errors like with other builtins that take variable names
wait -p invalid-varname
readonly WV
wait -p WV
