#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

jobs
echo $?

# a no-such-job error, since we can use job control notation without job control
wait %1

# make sure we can't fg a job started when job control was not active
sleep 20 &
pid=$!
fg %1
# make sure the killed processes don't cause a message
exec 5>&2
exec 2>/dev/null
kill -n9 $pid
wait $pid   # make sure we reap the processes while stderr is still redirected

sleep 30 &
pid2=$!
kill -sHUP $pid2
wait $pid2
exec 2>&5
unset -v pid pid2

################################################################################
################################################################################
################################################################################
################################################################################

echo wait-errors
wait 1-1
wait -- -4

#############################
#########
#########
####

########################################
###################
####

##############################
#####################
####

##########################
####

######################
#############################################################

