#! /bin/sh
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

: ${TMPDIR:=/tmp}

for BUILD_DIR in \
    "${BUILD_DIR:-..}" \
    .. \
    /usr/local/build/bash/bash-current \
    ../.. \
    ../.build \
    .build/.. \
    ../../BUILD/bash \
    ../BUILD \
    $TMPDIR/bash-build \
;do
  [ -f "$BUILD_DIR/config.status" ] &&
  [ -d "$BUILD_DIR/tests" ] &&
  [ -f "$BUILD_DIR/bash" ] &&
  break
done || {
  echo >&2 'Cannot guess BUILD_DIR; please set and export it before calling this script'
  exit 2
}

: ${THIS_SH:=$BUILD_DIR/bash}

# Some tests use ‘cd’, so make sure THIS_SH is an absolute path
case $THIS_SH in
  /*) ;;
  *)  THIS_SH=$PWD/$THIS_SH
esac

PATH=$BUILD_DIR:$PWD:$PATH	# just to get recho/zecho/printenv if not run via `make tests'

# basic /bin/sh syntax
SUFFIX=$( ${THIS_SH} -c 'echo $(( $RANDOM + $BASHPID ))' )

BASH_TSTOUT=${TMPDIR}/bashtst-$SUFFIX	# for now

export BASH_TSTOUT BUILD_DIR PATH THIS_SH TMPDIR

trap 'rm -f $BASH_TSTOUT ; exit' 1 2 3 15
trap 'rm -f $BASH_TSTOUT' 0

# unset BASH_ENV only if it is set
[ "${BASH_ENV+set}" = set ] && unset BASH_ENV
# can't reliably do it for SHELLOPTS; SHELLOPTS is readonly in bash
if [ "${BASH_VERSION+set}" = set ]; then
  export -n SHELLOPTS	# just make sure its not exported
  set +o posix
  typeset -p SHELLOPTS
else
  [ "${SHELLOPTS+set}" = set ] && unset SHELLOPTS 2>/dev/null
fi

# ditto for BASHOPTS, which is also readonly in bash
if [ "${BASH_VERSION+set}" = "set" ]; then
  export -n BASHOPTS	# just make sure its not exported
else
  [ "${BASHOPTS+set}" = "set" ] && unset BASHOPTS 2>/dev/null
fi

${THIS_SH} ./version

rm -f ${BASH_TSTOUT}

export TAB='	'

echo Any output from any test, unless otherwise noted, indicates a possible anomaly

# keep track of passed and failed tests and report them
if [ -t 1 ]; then
  if type -P tput >/dev/null; then
#   CSTART=$(tput bold ; tput setaf 15 ; tput setab 1) CEND=$(tput sgr0)
    CSTART=$(tput bold ; tput setab 9 ; tput setaf 7) CEND=$(tput sgr0)
  else
    # can't rely on having $'...' or printf understanding \e
    # bright red background, white foreground text
    CSTART=$(printf '\033[1;101;37m') CEND=$(printf '\033[0m')
  fi
else
  CSTART= CEND=
fi
export CSTART CEND

passed=0
total=0
failed=0

if [ -n "$BASH_TSTOUT_SAVEDIR" ] && [ -d "$BASH_TSTOUT_SAVEDIR" ]; then
	echo "Using $BASH_TSTOUT_SAVEDIR to save output from failed tests"
else
	unset BASH_TSTOUT_SAVEDIR
fi

# One or more tests may be specified on the command line, or run all of them if
# none are specified.

[ $# = 0 ] && set run-*

for x do
  case $x in
    $0|\
    ${0##*/}|\
    run-all|\
    run-gprof|\
    run-minimal|\
    *.orig|\
    *.save|\
    *~)
      continue ;;
  esac

  echo
  echo RUNNING $x
  total=$(( $total + 1 ))
  if sh $x; then
    passed=$(( $passed + 1 ))
  else
    echo "${CSTART}${x}: NON-ZERO exit status $?${CEND}"
    if [ -n "$BASH_TSTOUT_SAVEDIR" ]; then
      mv ${BASH_TSTOUT} ${BASH_TSTOUT_SAVEDIR}/${x}-${SUFFIX}
      echo "${CSTART}output saved to ${BASH_TSTOUT_SAVEDIR}/${x}-${SUFFIX}${CEND}"
    elif [ $failed -eq 1 ]; then
      echo "${CSTART}Set environment variable BASH_TSTOUT_SAVEDIR to a directory to save failed test output${CEND}"
    fi
    failed=$(( $failed + 1 ))
  fi
  rm -f ${BASH_TSTOUT}
  ;;
esac
done

echo "${CSTART}${passed}/${total} tests succeeded${CEND}"
exit $failed
