#! /bin/sh
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

with_gprof=yes exec run-all "$@"

: ${TMPDIR:=/tmp}
export TMPDIR

# basic /bin/sh syntax
SUFFIX=$( ${THIS_SH} -c 'echo $(( $RANDOM + $BASHPID ))' )

BASH_TSTOUT=${TMPDIR}/bashtst-$SUFFIX	# for now
export BASH_TSTOUT

trap 'rm -f $BASH_TSTOUT ; exit 1' 1 2 3 15
trap 'rm -f $BASH_TSTOUT' 0

PATH=.:$PATH	# just to get the right version of recho/zecho/printenv if not run via 'make tests'
export PATH	# should be redundant

# unset BASH_ENV only if it is set
[ "${BASH_ENV+set}" = set ] && unset BASH_ENV

# ditto for SHELLOPTS & BASHOPTS, which are both readonly in bash
[ "${SHELLOPTS+set}" = set ] &&
if [ "${BASH_VERSION+set}" = set ]; then
	export -n SHELLOPTS	# can't unset, so just make sure its not exported
	set +o posix
	typeset -p SHELLOPTS
else
	unset SHELLOPTS 2>/dev/null
fi
[ "${BASHOPTS+set}" = set ] &&
if [ "${BASH_VERSION+set}" = set ]; then
	export -n BASHOPTS	# can't unset, so just make sure its not exported
	set +o posix
	typeset -p BASHOPTS
else
	unset BASHOPTS 2>/dev/null
fi

: ${THIS_SH:=../bash}
export THIS_SH

: ${BUILD_DIR:=..}
export BUILD_DIR

if [ "$with_gprof" = yes ]
then
	GPROF=gprof

	rm -f gmon.sum
	# prime the pump; ${GPROF} complains if gmon.sum is empty
	[ -f gmon.out ] && ${GPROF} -s ${THIS_SH} gmon.out >/dev/null

	export GMON_OUT_PREFIX=bash
fi

${THIS_SH} ./version

rm -f "$BASH_TSTOUT"

echo Any output from any test, unless otherwise noted, indicates a possible anomaly

for x in run-*
do
	case $x in
	$0|run-all|run-minimal|run-gprof)	;;
	*.orig|*~) ;;
	*)	echo $x ; sh $x
		if [ "$with_gprof" = yes ]
		then
			if [ -f $TMPDIR/gmon.out ]; then
				if [ -f gmon.out ]; then
					${GPROF} -s ${THIS_SH} gmon.sum ${GMON_OUT_PREFIX}.[0-9]* $TMPDIR/${GMON_OUT_PREFIX}.[0-9]* >/dev/null
				else
					${GPROF} -s ${THIS_SH} gmon.sum $TMPDIR/${GMON_OUT_PREFIX}.[0-9]* >/dev/null
				fi
			else
				${GPROF} -s ${THIS_SH} gmon.sum ${GMON_OUT_PREFIX}.[0-9]* >/dev/null
			fi
			rm -f $TMPDIR/${GMON_OUT_PREFIX}.[0-9]* ${GMON_OUT_PREFIX}.[0-9]*
		fi
		;;
	esac
done

if [ "$with_gprof" = yes ]
then
	if [ -f ./-specialname.gmon ]; then
		${GPROF} -s ${THIS_SH} gmon.sum ./-specialname.gmon > /dev/null
		rm -f ./-specialname.gmon
	fi
	if [ -f ./ohio-state.gmon ]; then
		${GPROF} -s ${THIS_SH} gmon.sum ./ohio-state.gmon > /dev/null
		rm -f ./ohio-state.gmon
	fi

	if [ -f specialname.gmon ]; then
		${GPROF} -s ${THIS_SH} gmon.sum ./specialname.gmon > /dev/null
		rm -f specialname.gmon
	fi
fi

exit 0
