#! /bin/sh
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# run-minimal - a version of run-all for shells configured with
#		--enable-minimal-config
#

[ $# = 0 ] &&
set -- --keep-results=no \
        run-comsub-eof run-comsub-posix run-dollars run-dynvar run-execscript \
        run-func run-getopts run-heredoc run-ifs-posix run-ifs-tests \
        run-input-test run-invert run-iquote run-more-exp run-nquote \
        run-posix2 run-posixpat run-posixpipe run-precedence run-quote \
        run-read run-rhs-exp run-strip run-tilde run-type

with_gprof=yes exec run-all "$@"
