#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#   See the GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, see <http://www.gnu.org/licenses/>.

# This doesn't work right on all Unix versions
if [ -d /dev/fd ] 
then
    # make sure process substitution runs the exit trap
    [[ -n $(< <(trap "cat /dev/fd/0" EXIT)) ]] <<<works && echo works || echo "fail :("
else
    echo works  # faking it
    # When run under “run-all”, write the following message into the summary
    # results file, rather than to stderr where it could cause a mismatch.
    ( exec 2>&3 ; echo >&2 'Skipping "cat /dev/fd/0" because /dev/fd does not exist on this system' )
fi

read foo < <(trap "echo bar" EXIT)
echo $foo

cat <(trap "echo bar" EXIT)

trap "echo bar" EXIT	#should proc subst inherit this?
cat <(echo foo ; exit 0;)

trap - 0
trap

cat <(echo foo; trap "echo bar" EXIT)

trap "echo bar" EXIT	#should proc subst inherit this?
cat <(echo foo)
