#!/bin/bash

#
# 50indent
#
# Use GNU indent to standardise the layout of C source files.
#
# This should be installed among the pre-commit hooks in .git-pre-commit.d/.
#
# Only consider C source files; ignore
# (1) filenames other than «*.[ch]», and
# (2) files that have been only partially cached
#     (either added and then changed again, or added using "git add -p")
#
# After running "indent", check that there are only whitespace changess.
#
# If the only changes are to whitespace, then add the file so that it is
# included in the commit.
#
# Fail if there are non whitespace changes, so that it becomes the user's
# choice how to resolve the conflict:
#
# (a) manually add the file as-is after "indent" processing; or
# (b) revert to the saved backup and make further adjustments, including
#
# possibly inserting «/* *NOINDENT* */» directives.
#

# NOTE TO FUTURE MAINTAINERS
#  Avoid using both "exit 0" and "return 0", as this script can be used both as
#  a file to source within the top level checker, and as a separate executable.

# Identify files that have been cached by using "git add"
readarray -td '' CachedFiles < <(
    git diff --cached --name-only -z **/*.[ch]
)
if (( ${#CachedFiles[@]} > 0 )) then

    # Identify files that have been only partially cached
    readarray -td '' PartlyCachedFiles < <(
        git diff --name-only -z "${CachedFiles[@]}"
    )

    # Take the complement to identify files that have been fully cached
    declare -A Status
    for f in "${PartlyCachedFiles[@]}"
    do
        Status[$f]=partial
    done
    FullyCachedFiles=()
    for f in "${CachedFiles[@]}"
    do
        if [[ Status[$f] != partial ]] then
            Status[$f]=full
            FullyCachedFiles+=("$f")
        fi
    done

    # If there are no fully cached files, avoid all further processing
    if (( ${#FullyCachedFiles[@]} > 0 )) then

        # Re-indent any files that were already fully cached. If "indent"
        # fails, return a non-zero status so that the commit won't proceed.

        indent "${FullyCachedFiles[@]}" || exit 1

        # Categorise fully cached files by whether "indent" makes changes
        # that "git diff -w" does or doesn't suppress.
        readarray -td '' DirtyCachedFiles < <(
            git diff --name-only -z "${FullyCachedFiles[@]}"
        )
        for f in "${DirtyCachedFiles[@]}"
        do
            Status[$f]=dirty
        done
        CleanCachedFiles=()
        for f in "${FullyCachedFiles[@]}"
        do
            if [[ Status[$f] != dirty ]] then
                CleanCachedFiles+=("$f")
            fi
        done

        (( ${#CleanCachedFiles[@]} )) &&
            git add "${CleanCachedFiles[@]}"

        if (( ${#DirtyCachedFiles[@]} )) then
            printf '\nSome files have changed in ways that are not ignored by “git diff -w”:\n\n'
            git diff --name-only -w "${DirtyCachedFiles[@]}"
            printf '\nPlease resolve all differences and then try “git commit” again.\nTo bypass these checks, use “git commit --no-verify”.\n\n'
            exit 1
        fi
    fi
fi
